target 'Catalog' do
  use_frameworks!

  pod 'RealmSwift'	
  pod 'Moya'
  pod 'Moya-ObjectMapper'
  pod 'SDWebImage'
  pod 'ImageSlideshow'
  pod "ImageSlideshow/SDWebImage"
  pod 'TextFieldEffects'
end
